version: '3.8'

services:

  nginx:
    container_name: nginx
    restart: always
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/app
    depends_on:
      - backend
    networks:
      - fastapi-network

  backend:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    command: 'sh -c "alembic upgrade head && python app/main.py --host 0.0.0.0 --port 8000"'
    depends_on:
      - fastapi-db
      - redis-cache
    networks:
      - fastapi-network
      

  fastapi-db:
    container_name: fastapi-db
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastapi-network
      
  redis-cache:
    image: redis:alpine
    hostname: redis-cache
    container_name: redis-cache
    restart: on-failure
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache:/data
    networks:
      - fastapi-network
      
  celery-worker:
    container_name: celery-worker
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile  
    command: celery -A app.tasks.configs worker --loglevel=info
    env_file:
      - .env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - .:/app
    depends_on:
      - fastapi-db
      - redis-cache
    networks:
      - fastapi-network
      
  celery-beat:
    container_name: celery-beat
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: celery -A app.tasks.configs beat --loglevel=info
    env_file:
      - .env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - .:/app
    depends_on:
      - fastapi-db
      - redis-cache
    networks:
      - fastapi-network

  flower:
    container_name: flower
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile     
    command: celery -A app.tasks.configs flower
    env_file:
      - .env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    depends_on:
      - backend
      - redis-cache
      - celery-worker
    networks:
      - fastapi-network

  adminer:
      image: adminer
      ports:
        - 5051:8080
      environment:
        ADMINER_DEFAULT_SERVER: fastapi-db
      depends_on:
        - fastapi-db
      networks:
        - fastapi-network

volumes:
  postgres_data:
  cache:
networks:
  fastapi-network: