apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: fastapi-namespace
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
  storageClassName: standard
